"
A trait for flexbox alignment
"
Trait {
	#name : #SBSTContentJustification,
	#category : #'Bootstrap5-Core-Traits'
}

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentAround [

	self class: 'justify-content-around'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentAroundLarge [

	self class: 'justify-content-lg-around'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentAroundMedium [

	self class: 'justify-content-md-around'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentAroundSmall [

	self class: 'justify-content-sm-around'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentAroundVeryLarge [

	self class: 'justify-content-xl-around'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentBetween [

	self class: 'justify-content-between'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentBetweenLarge [

	self class: 'justify-content-lg-between'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentBetweenMedium [

	self class: 'justify-content-md-between'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentBetweenSmall [

	self class: 'justify-content-sm-between'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentBetweenVeryLarge [

	self class: 'justify-content-xl-between'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentCenter [

	self class: 'justify-content-center'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentCenterLarge [

	self class: 'justify-content-lg-center'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentCenterMedium [

	self class: 'justify-content-md-center'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentCenterSmall [

	self class: 'justify-content-sm-center'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentCenterVeryLarge [

	self class: 'justify-content-xl-center'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentEnd [

	self class: 'justify-content-end'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentEndLarge [

	self class: 'justify-content-lg-end'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentEndMedium [

	self class: 'justify-content-md-end'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentEndSmall [

	self class: 'justify-content-sm-end'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentEndVeryLarge [

	self class: 'justify-content-xl-end'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentStart [

	self class: 'justify-content-start'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentStartLarge [

	self class: 'justify-content-lg-start'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentStartMedium [

	self class: 'justify-content-md-start'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentStartSmall [

	self class: 'justify-content-sm-start'
]

{ #category : #'alignment horizontal' }
SBSTContentJustification >> justifyContentStartVeryLarge [

	self class: 'justify-content-xl-start'
]
