"
Vertical alignment of items in a row
"
Trait {
	#name : #SBSTRowItemAlignment,
	#category : #'Bootstrap5-Core-Traits'
}

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsBaseline [

	self class: 'align-items-baseline'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsBaselineLarge [

	self class: 'align-items-lg-baseline'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsBaselineMedium [

	self class: 'align-items-md-baseline'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsBaselineSmall [

	self class: 'align-items-sm-baseline'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsBaselineVeryLarge [

	self class: 'align-items-xl-baseline'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsCenter [

	self class: 'align-items-center'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsCenterLarge [

	self class: 'align-items-lg-center'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsCenterMedium [

	self class: 'align-items-md-center'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsCenterSmall [

	self class: 'align-items-sm-center'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsCenterVeryLarge [

	self class: 'align-items-xl-center'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsEnd [

	self class: 'align-items-end'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsEndLarge [

	self class: 'align-items-lg-end'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsEndMedium [

	self class: 'align-items-md-end'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsEndSmall [

	self class: 'align-items-sm-end'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsEndVeryLarge [

	self class: 'align-items-xl-end'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsStart [

	self class: 'align-items-start'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsStartLarge [

	self class: 'align-items-lg-start'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsStartMedium [

	self class: 'align-items-md-start'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsStartSmall [

	self class: 'align-items-sm-start'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsStartVeryLarge [

	self class: 'align-items-xl-start'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsStretch [

	self class: 'align-items-stretch'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsStretchLarge [

	self class: 'align-items-lg-stretch'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsStretchMedium [

	self class: 'align-items-md-stretch'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsStretchSmall [

	self class: 'align-items-sm-stretch'
]

{ #category : #'alignment vertical' }
SBSTRowItemAlignment >> alignItemsStretchVeryLarge [

	self class: 'align-items-xl-stretch'
]
