"
A trait for flexbox container behaviour
"
Trait {
	#name : #SBSTFlexboxContainer,
	#category : #'Bootstrap4-Core-Traits'
}

{ #category : #container }
SBSTFlexboxContainer >> flex [

	self class: 'd-flex'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexColumn [

	self class: 'flex-column'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexColumnLarge [

	self class: 'flex-lg-column'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexColumnLargeReverse [

	self class: 'flex-lg-column-reverse'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexColumnMedium [

	self class: 'flex-md-column'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexColumnMediumReverse [

	self class: 'flex-md-column-reverse'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexColumnReverse [

	self class: 'flex-column-reverse'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexColumnSmall [

	self class: 'flex-sm-column'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexColumnSmallReverse [

	self class: 'flex-sm-column-reverse'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexColumnVeryLarge [

	self class: 'flex-xl-column'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexColumnVeryLargeReverse [

	self class: 'flex-xl-column-reverse'
]

{ #category : #container }
SBSTFlexboxContainer >> flexInline [

	self class: 'd-inline-flex'
]

{ #category : #container }
SBSTFlexboxContainer >> flexLarge [

	self class: 'd-lg-flex'
]

{ #category : #container }
SBSTFlexboxContainer >> flexLargeInline [

	self class: 'd-lg-inline-flex'
]

{ #category : #container }
SBSTFlexboxContainer >> flexMedium [

	self class: 'd-md-flex'
]

{ #category : #container }
SBSTFlexboxContainer >> flexMediumInline [

	self class: 'd-md-inline-flex'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexRow [

	self class: 'flex-row'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexRowLarge [

	self class: 'flex-lg-row'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexRowLargeReverse [

	self class: 'flex-lg-row-reverse'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexRowMedium [

	self class: 'flex-md-row'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexRowMediumReverse [

	self class: 'flex-md-row-reverse'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexRowReverse [

	self class: 'flex-row-reverse'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexRowSmall [

	self class: 'flex-sm-row'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexRowSmallReverse [

	self class: 'flex-sm-row-reverse'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexRowVeryLarge [

	self class: 'flex-xl-row'
]

{ #category : #'alignment direction' }
SBSTFlexboxContainer >> flexRowVeryLargeReverse [

	self class: 'flex-xl-row-reverse'
]

{ #category : #container }
SBSTFlexboxContainer >> flexSmall [

	self class: 'd-sm-flex'
]

{ #category : #container }
SBSTFlexboxContainer >> flexSmallInline [

	self class: 'd-sm-inline-flex'
]

{ #category : #container }
SBSTFlexboxContainer >> flexVeryLarge [

	self class: 'd-xl-flex'
]

{ #category : #container }
SBSTFlexboxContainer >> flexVeryLargeInline [

	self class: 'd-xl-inline-flex'
]
