Extension { #name : #WAImageTag }

{ #category : #'*Bootstrap4-Core' }
WAImageTag >> centered [

	self class: 'mx-auto d-block'
]

{ #category : #'*Bootstrap4-Core' }
WAImageTag >> circle [

	self class: 'rounded-circle'
]

{ #category : #'*Bootstrap4-Core' }
WAImageTag >> floatLeft [

	self class: 'float-left'
]

{ #category : #'*Bootstrap4-Core' }
WAImageTag >> floatRight [

	self class: 'float-right'
]

{ #category : #'*Bootstrap4-Core' }
WAImageTag >> rounded [

	self class: 'rounded'
]

{ #category : #'*Bootstrap4-Core' }
WAImageTag >> thumbnail [

	self class: 'img-thumbnail'
]
